### ISSUE TITLE
No output using cl version

### ISSUE THREAD

**Issue by jeffabruce** [jyapayne/Web2Executable#94]
I was unable to get the command line version to export anything.

After issuing a command very similar to the one in the README, I get no errors, but nothing is created. I saw the issue related to improperly uninstalled node packages, but I don't think I have that as an issue. My system has a pretty fresh install of Node. I did find the error log had some interesting things in it (like what appears to be hard-coded references to your user folder).

I was able to make the GUI version produce something, but I had issues with it as well. However, I will create a separate issue for it.

I can't attached files so here is the text from the log file:
Downloading file http://dl.nwjs.io/v0.12.3/node-webkit-v0.12.3-win-ia32.zip.
INFO       2015-11-10 12:25:08,255 <string>.py: 886 download_file - Downloading file http://dl.nwjs.io/v0.12.3/node-webkit-v0.12.3-win-ia32.zip.
Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 919, in download_file
IOError: [Errno 22] invalid mode ('ab') or filename: u'C:\\Users\\jbruce\\AppData\\Local\\Web2Executable\\Web2Executable\x0ciles\\downloads\\.tmp.nwjs-v0.12.3-win-ia32.zip'

ERROR      2015-11-10 12:25:08,505 <string>.py: 370 show_error - Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 919, in download_file
IOError: [Errno 22] invalid mode ('ab') or filename: u'C:\\Users\\jbruce\\AppData\\Local\\Web2Executable\\Web2Executable\x0ciles\\downloads\\.tmp.nwjs-v0.12.3-win-ia32.zip'

Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-ia32.zip.
INFO       2015-11-10 12:25:47,079 <string>.py: 886 download_file - Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-ia32.zip.
Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 919, in download_file
IOError: [Errno 22] invalid mode ('ab') or filename: u'C:\\Users\\jbruce\\AppData\\Local\\Web2Executable\\Web2Executable\x0ciles\\downloads\\.tmp.node-webkit-v0.10.5-win-ia32.zip'

ERROR      2015-11-10 12:25:47,220 <string>.py: 370 show_error - Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 919, in download_file
IOError: [Errno 22] invalid mode ('ab') or filename: u'C:\\Users\\jbruce\\AppData\\Local\\Web2Executable\\Web2Executable\x0ciles\\downloads\\.tmp.node-webkit-v0.10.5-win-ia32.zip'

Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-ia32.zip.
INFO       2015-11-10 12:26:28,009 <string>.py: 886 download_file - Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-ia32.zip.
Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 919, in download_file
IOError: [Errno 22] invalid mode ('ab') or filename: u'C:\\Users\\jbruce\\AppData\\Local\\Web2Executable\\Web2Executable\x0ciles\\downloads\\.tmp.node-webkit-v0.10.5-win-ia32.zip'

ERROR      2015-11-10 12:26:28,226 <string>.py: 370 show_error - Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 919, in download_file
IOError: [Errno 22] invalid mode ('ab') or filename: u'C:\\Users\\jbruce\\AppData\\Local\\Web2Executable\\Web2Executable\x0ciles\\downloads\\.tmp.node-webkit-v0.10.5-win-ia32.zip'

Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-x64.zip.
INFO       2015-11-10 12:31:54,983 <string>.py: 886 download_file - Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-x64.zip.
Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 918, in download_file
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 154, in urlopen
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 437, in open
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 550, in http_response
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 475, in error
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 409, in _call_chain
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 558, in http_error_default
HTTPError: HTTP Error 404: Not Found

ERROR      2015-11-10 12:31:55,173 <string>.py: 370 show_error - Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 918, in download_file
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 154, in urlopen
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 437, in open
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 550, in http_response
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 475, in error
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 409, in _call_chain
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 558, in http_error_default
HTTPError: HTTP Error 404: Not Found

Getting versions...
INFO       2015-11-10 12:35:11,180 command_line.py: 377 get_versions - Getting versions...
Loading package.json
INFO       2015-11-10 12:36:24,247 command_line.py: 433 load_package_json - Loading package.json
Generating package.json...
INFO       2015-11-10 12:38:05,322 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:19,029 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:28,506 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:31,247 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:40,418 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:40,668 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:40,779 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:40,966 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:41,154 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:46,635 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:46,720 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:46,798 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:38:46,953 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:39:09,404 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:39:24,595 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:40:17,766 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Copying file D:\Projects\Research\web2exe\test\resources\someicon.png to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:40:17,780 command_line.py: 844 copy_files_to_project_folder - Copying file D:\Projects\Research\web2exe\test\resources\someicon.png to D:\Projects\Research\web2exe\test\source
Copying file D:\Projects\Research\web2exe\test\resources\someicon.png to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:40:17,780 command_line.py: 844 copy_files_to_project_folder - Copying file D:\Projects\Research\web2exe\test\resources\someicon.png to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:40:17,780 command_line.py: 452 generate_json - Generating package.json...
['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
ERROR      2015-11-10 12:40:21,530 command_line.py: 757 make_output_dirs - ['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
Generating package.json...
INFO       2015-11-10 12:41:34,530 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:39,644 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,188 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,252 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,299 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,345 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,392 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,438 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,517 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,611 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:41:43,736 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:42:05,493 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:42:05,493 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,223 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,259 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,275 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,322 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,352 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,414 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,461 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,555 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:43:37,628 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:43:40,566 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:43:40,566 command_line.py: 452 generate_json - Generating package.json...
['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
ERROR      2015-11-10 12:43:44,316 command_line.py: 757 make_output_dirs - ['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
Generating package.json...
INFO       2015-11-10 12:44:19,144 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:44:19,193 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:44:19,232 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:44:19,272 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:44:19,328 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:44:21,361 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:44:28,742 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:44:28,742 command_line.py: 452 generate_json - Generating package.json...
['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
ERROR      2015-11-10 12:44:32,838 command_line.py: 757 make_output_dirs - ['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
Generating package.json...
INFO       2015-11-10 12:45:05,494 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:45:05,559 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:45:05,631 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:45:05,687 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:45:05,799 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:45:09,763 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:45:09,763 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:45:38,575 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:45:43,224 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:45:44,904 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:46:14,562 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:46:14,562 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:46:55,588 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:47:05,561 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:47:05,562 command_line.py: 452 generate_json - Generating package.json...
['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 663, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\shutil", line 252, in rmtree\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\shutil", line 250, in rmtree\n', "WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\\\Projects\\\\Research\\\\web2exe\\\\test\\\\release\\\\source\\\\windows-x64\\\\icudtl.dat'\n"]
ERROR      2015-11-10 12:47:08,111 command_line.py: 757 make_output_dirs - ['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 663, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\shutil", line 252, in rmtree\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\shutil", line 250, in rmtree\n', "WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\\\Projects\\\\Research\\\\web2exe\\\\test\\\\release\\\\source\\\\windows-x64\\\\icudtl.dat'\n"]
Generating package.json...
INFO       2015-11-10 12:47:18,061 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:47:18,117 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:47:18,188 command_line.py: 452 generate_json - Generating package.json...
Generating package.json...
INFO       2015-11-10 12:47:18,276 command_line.py: 452 generate_json - Generating package.json...
Copying files to D:\Projects\Research\web2exe\test\source
INFO       2015-11-10 12:47:20,760 command_line.py: 836 copy_files_to_project_folder - Copying files to D:\Projects\Research\web2exe\test\source
Generating package.json...
INFO       2015-11-10 12:47:20,776 command_line.py: 452 generate_json - Generating package.json...
['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
ERROR      2015-11-10 12:47:24,329 command_line.py: 757 make_output_dirs - ['Traceback (most recent call last):\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 730, in make_output_dirs\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\Web2Exe\\out00-PYZ.pyz\\command_line", line 812, in compress_nw\n', "WindowsError: [Error 5] Access is denied: 'C:\\\\PROGRA~2\\\\Web2Exe\\\\files\\\\compressors\\\\upx-win.exe'\n"]
Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-x64.zip.
INFO       2015-11-10 12:53:27,270 <string>.py: 886 download_file - Downloading file http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-win-x64.zip.
Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 918, in download_file
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 154, in urlopen
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 437, in open
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 550, in http_response
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 475, in error
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 409, in _call_chain
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 558, in http_error_default
HTTPError: HTTP Error 404: Not Found

ERROR      2015-11-10 12:53:27,490 <string>.py: 370 show_error - Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 918, in download_file
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 154, in urlopen
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 437, in open
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 550, in http_response
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 475, in error
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 409, in _call_chain
  File "C:\Users\Joey\Downloads\Web2Executable\build\web2exe-win\out00-PYZ.pyz\urllib2", line 558, in http_error_default
HTTPError: HTTP Error 404: Not Found

**Comment by jyapayne** [comment]
It could be that you haven't updated the CLI version in a while. I update the CLI version every time I do a GUI update, but the link stays the same. Try re-downloading the CLI version from the downloads page and see if that helps. If it doesn't, let me know!

As for the hard coded references, they are not actually hard coded. The packaging system I use creates a virtual file system that mimics my file system so that when an error occurs, I can quickly locate where in the code the error happened :)

**Comment by jyapayne** [comment]
Ah, something seems to be wrong on my end. The url of the download is incorrect. I'll check it out for you :)

**Comment by jyapayne** [comment]
For now, if you open up the directory that Web2Exe is installed in and then open up `files\settings.cfg` with notepad, and change this:

```
win_32_dir_prefix = 'node-webkit-v{}-win-ia32'
mac_32_dir_prefix = 'node-webkit-v{}-osx-ia32'
linux_32_dir_prefix = 'node-webkit-v{}-linux-ia32'

win_64_dir_prefix = 'node-webkit-v{}-win-x64'
mac_64_dir_prefix = 'node-webkit-v{}-osx-x64'
linux_64_dir_prefix = 'node-webkit-v{}-linux-x64'
```

to this:

```
win_32_dir_prefix = 'nwjs-v{}-win-ia32'
mac_32_dir_prefix = 'nwjs-v{}-osx-ia32'
linux_32_dir_prefix = 'nwjs-v{}-linux-ia32'

win_64_dir_prefix = 'nwjs-v{}-win-x64'
mac_64_dir_prefix = 'nwjs-v{}-osx-x64'
linux_64_dir_prefix = 'nwjs-v{}-linux-x64'
```

That should fix the issue while I update the downloads :)

**Comment by jeffabruce** [comment]
That didn't quite solve the issue. At first I was specifying the nwjs version "0.10.5" as used in the examples, but those files don't seem to be available on dl.nwjs.io. So, I set the version to "0.12.3" instead and got farther. In the log file I now see:
Traceback (most recent call last):
  File "<string>", line 421, in download_file_with_error_handling
  File "<string>", line 919, in download_file
IOError: [Errno 22] invalid mode ('ab') or filename: u'C:\\Users\\jbruce\\AppData\\Local\\Web2Executable\\Web2Executable\x0ciles\\downloads\\.tmp.nwjs-v0.12.3-win-x64.zip'

**Comment by jyapayne** [comment]
Yeah, it looks like the path has some issues. I'm not sure how this never came up before, but in the path above `...\Web2Executable\x0ciles\...` is supposed to be `...\Web2Executable\files\...`. There's something wrong with the windows path being set. I'm looking into it!

**Comment by jyapayne** [comment]
Can you try downloading the latest version again? I updated it [here](http://www.mediafire.com/download/r9rawa9qorlfa79/Web2ExeWin-CMD.zip). It seems to work for me now, but I'd like to see if it works for you as well :)

**Comment by jeffabruce** [comment]
I got further, but still no output files and this error in the log:
['Traceback (most recent call last):\n', '  File "<string>", line 635, in make_output_dirs\n', '  File "<string>", line 844, in copy_files_to_project_folder\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\web2exe-win\\out00-PYZ.pyz\\shutil", line 119, in copy\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\web2exe-win\\out00-PYZ.pyz\\shutil", line 82, in copyfile\n', "IOError: [Errno 2] No such file or directory: u'source\\\\index.htm'\n"]
ERROR      2015-11-10 15:06:31,505 <string>.py: 758 make_output_dirs - ['Traceback (most recent call last):\n', '  File "<string>", line 635, in make_output_dirs\n', '  File "<string>", line 844, in copy_files_to_project_folder\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\web2exe-win\\out00-PYZ.pyz\\shutil", line 119, in copy\n', '  File "C:\\Users\\Joey\\Downloads\\Web2Executable\\build\\web2exe-win\\out00-PYZ.pyz\\shutil", line 82, in copyfile\n', "IOError: [Errno 2] No such file or directory: u'source\\\\index.htm'\n"]

**Comment by jyapayne** [comment]
Make sure that `source\index.htm` (maybe you meant `source\index.html`?) exists inside your project folder. Even though it's probably confusing, the command line version of Web2Exe expects the files to be specified relative to the project directory.

So if your project was located at `C:\MyProject\`, Web2Exe must be invoked with

```web2exe.exe C:\MyProject\ --main source\index.htm --export-to windows-x32 --nw-version 0.12.3```

 where `source\index.htm` must be in  `C:\MyProject\` ( ie: `C:\MyProject\source\index.htm`).

**Comment by jyapayne** [comment]
I've updated the CLI version again to show progress text (it was supposed to before, but there was a bug). Also, you can run it with the --verbose flag to see errors instead of the error.log.

**Comment by jeffabruce** [comment]
OK, still making progress.

My folder structure looks like this:
<some_path>\web2exe-win.exe
<some_path>\files
<some_path>\source\index.htm
<some_path>\source\<other files>
<some_path>\release

So, I actually put a local copy of the web2exe-win EXE in the "project root".

Within a command prompt where the CWD is <some_path>, I executed:
web2exe-win.exe source  --output-dir release --main source\index.htm --export-to windows-x32 --nw-version 0.12.3
And it did not work. However, if I removed the reference to "source" in the "--main" option, it worked.

After that change, I did end up with a subfolder or the "release" folder containing the "source.exe" EXE that is my app.

Now, it didn't entirely work so I have more work to do. This code loads a local XML file and I have a feeling like it is not being found when I run the EXE.
- Are ALL files in the "source" folder (and subfolders) bound up into the generated EXE?
- Do I need a special protocol or something to access a "local" XML file?
- Is there some flag or code to allow me to debug using the Chrome "Developer Tools" window (where I could see the console, CSS, etc.)
- I see that the resulting EXE is 174MB. That's pretty huge. In some of the other solutions I'm evaluating, I have seen that be 40MB-70MB (compressing down to as little as 18MB in a self-extracting EXE). Are there any options to get the generated output any smaller?

If you prefer to have this conversation outside of this incident thread, may I send you an email?

**Comment by jyapayne** [comment]
> My folder structure looks like this:
> \web2exe-win.exe
> \files
> \source\index.htm
> \source<other files>
> \release
> 
> So, I actually put a local copy of the web2exe-win EXE in the "project root".
> 
> Within a command prompt where the CWD is , I executed:
> web2exe-win.exe source --output-dir release --main source\index.htm --export-to windows-x32 --nw-version 0.12.3
> And it did not work. However, if I removed the reference to "source" in the "--main" option, it worked.

Yeah, that's what I mean by slightly confusing :) Here, your "project root" is actually the `source` directory, so you have to specify `index.htm` instead of `source\index.htm`.

> If you prefer to have this conversation outside of this incident thread, may I send you an email?

Yes, you may send an email :)

>I see that the resulting EXE is 174MB. That's pretty huge. In some of the other solutions I'm evaluating, I have seen that be 40MB-70MB (compressing down to as little as 18MB in a self-extracting EXE). Are there any options to get the generated output any smaller?

I've updated the CLI once more to (hopefully) remove the output folder before exporting (because before I would simply append to the current exe, which made it balloon up in size), or if you delete the output folder manually and export again, you should see the regular 40-70 MB in size. This solution should be equivalent to the others :)

Answers to your other questions (you can respond to these via my email):

1) Yes. All files are considered static once packed up and cannot be modified.
2) In order to access an external file, you have to use some node.js code. We can discuss once you send me the email.
3) The developer tools can be accessed by enabling the toolbar with the `--toolbar` option.

**Comment by jyapayne** [comment]
Please download the CLI version again. I apologize for all this version updating. Hotfixes often lead to this kind of thing :)
